### ISSUE TITLE
Feature Request: Standard Events

### ISSUE THREAD

**Issue by geeknikolai** [martonsagi/al-object-designer#19]
Have been using your app mostly for generating my Event subscriber signatures - and even for just that it is awesome thank you. 

However, unless I'm missing something, this doesn't include the standard Events (e.g. Record.OnInsert or Field.OnValidate) - not sure how to include them without making the Event list messy but it would be very useful.

**Comment by martonsagi** [comment]
Standard events are not listed in the Symbol packages where I extract events from, hence the absence of them.

It's possible to generate Record/Field events, however it may have a notable performance impact. Doing a quick calculation, we are talking about ~27 000 additional events in a W1 database. We'll see how it works out :D

**Comment by martonsagi** [comment]
There are much more events then I anticipated at first. 64K!
Searching and browsing events became very slow. Reading the cached results (38MB) takes longer than generating standard events on the fly. :)

I continue thinking on how to optimize the listing part.

![image](https://user-images.githubusercontent.com/18100709/52654978-76687a80-2ef3-11e9-9a5f-49dcab4e894f.png)

**Comment by geeknikolai** [comment]
I'd be very happy with them generated on the fly, they don't have to be searchable. 

Maybe off the Assist Edit on the Table list - generate a file with all the Event Subscribers for the Table and it's Fields - like you have "New Card" at the moment.

**Comment by martonsagi** [comment]
Took some time but it's finally done as of v0.1.4. You can choose from standard events for tables and pages as well.
More details here: https://www.linkedin.com/pulse/subscribing-events-al-object-designer-m%C3%A1rton-s%C3%A1gi/
