### ISSUE TITLE
Feature Request: Implement Object Designer

### ISSUE THREAD

**Issue by stefanoPrimo** [martonsagi/al-object-designer#20]
Hi,
I think that it will be very helpful if, in the object designer, there is an option for creating TableExt and PageExtension. It will be a lot easier and a lot fast.

Thanks

**Comment by martonsagi** [comment]
Hi,

Thanks! So obvious.. but still a missing feature!
I have added this to the latest [0.0.7-alpha build](https://github.com/martonsagi/al-object-designer/blob/0.0.7-dev/custom-builds/al-object-designer-0.0.7-alpha.7.vsix) :)

![image](https://user-images.githubusercontent.com/18100709/56855191-5e759400-6943-11e9-925b-ef5cb02e68b7.png)
Sorry, the context menu design needs to be worked on. A casualty of the great re-design.

**Comment by stefanoPrimo** [comment]
Thanks, after downloading the Alpha I've seen that [https://github.com/martonsagi/al-object-designer/issues/23 ](url)
