### ISSUE TITLE
Feature Request: Automatically add page field caption

### ISSUE THREAD

**Issue by pcucuk** [martonsagi/al-object-designer#21]
It would be nice if, after creating a page from table, the fields gets assigned default caption based on the field name.

Current generated code:
```
field("SomeField"; "SomeField")
{
                   
}
```

Requested:
```
field("SomeField"; "SomeField")
{
        Caption = 'SomeField';
}
```

Loving the extension by the way :)

**Comment by martonsagi** [comment]
Hi,

I'm not sure in which case would this be useful. In the background, Page field captions are inherited from table field captions. So if you have captions set on table fields, you don't necessarily need to define and maintain captions on pages as well.

How about adding the table field caption as a commented out property?

Source Table:
```
field(15; "SomeField"; Code[20])
{
    Caption = 'Some Caption';
}
```

Generated Page:
```
field("SomeField"; "SomeField")
{
    //Caption = 'Some Caption';
}
```

**Comment by pcucuk** [comment]
I never thought to check, but I just always assumed that I needed to add the caption property else it wouldn't be included in the translation.xliff file. I'll check when I have the time and let you know.
