### ISSUE TITLE
Support for Multi-Root Workspaces

### ISSUE THREAD

**Issue by marknitek** [martonsagi/al-object-designer#22]
We use multi-root workspaces because we have several dependant apps. This works very well but the object designer does not like that (it shows "discovering objects..." but then nothing happens. Opening just one single app folder works as intended).

Furthermore the .alcache folder will be created in the first root folder instead of the one i'am currently working on. 

I think it should be possible to open the object designer based on the context on the current root folder i'am working on right now. Or maybe let me select the folder/context i want to show the designer for.

**Comment by martonsagi** [comment]
Multi-root support is a main goal that I thought is working well. Although, I have faced similar issues myself when started working on a real-life multi-root project :)

There are several alpha build in the 0.0.7-dev branch, where fixes were made in connection with "discovering objects" and multi-root issues. [Latest 0.0.7-alpha.9 build](https://github.com/martonsagi/al-object-designer/blob/0.0.7-dev/custom-builds/al-object-designer-0.0.7-alpha.9.vsix)

In the new build it works as follows:
1. First workspace folder is regarded as the main folder where .alcache folder is created
2. Downloaded Symbols are collected and processed from all workspace folders
3. Fixed: only distinct symbols are processed to avoid duplications
4. Object Designer windows shows all objects in the workspace, regardless of the currently selected context. So you can oversee the entire project-set
5. In the new alpha version "Application" column has correct values, so it's easy to see where an object belongs to.


Perhaps, an extension setting would be better if you want to override the path of .alcache folder?
