### ISSUE TITLE
Run Query

### ISSUE THREAD

**Issue by matteomontanari** [martonsagi/al-object-designer#25]
Hi

On "Object designer list" interface we can run tables pages and report but this option is not available for queries.

/?tenant=default&Query=50000 
is a valid url :)

Thank you in advance

Matteo

**Comment by martonsagi** [comment]
Hi,

Indeed, thank you for bringing this to my attention! Same goes for XmlPorts. Will be part of next release :)

**Comment by martonsagi** [comment]
Just realized that XmlPorts cannot be run without external solution. :( Anyway, running queries is working with newer 0.1.0-beta builds.
