### ISSUE TITLE
Export Object List

### ISSUE THREAD

**Issue by MBK75** [martonsagi/al-object-designer#29]
Hi there, great tool!  It would be great if there was an ability to export the Object Designer results to a file.  When I copy/paste, it only selects the rows visible in VS Code currently.  This is more of an ask than an issue.

**Comment by martonsagi** [comment]
Thank you!

I have changed the datagrid component in the next version, so it will be possible to export list contents into CSV. Export function takes active filters or search values into account.

![image](https://user-images.githubusercontent.com/18100709/68550948-fdf20400-0407-11ea-9a3f-8fb41f273e73.png)
