### ISSUE TITLE
Error in Column Name

### ISSUE THREAD

**Issue by yannstlo** [martonsagi/al-object-designer#38]
The name 'Prepmt__Payment_Discount_%' cannot be used as an identifier because it does not comply with the Common Language SpecificationAL(AL0379)

Some characters are not supported by AL in column names when doing report creation off of tables.
- dash / hyphen -
- parentheses ( )
- Percentage sign %

These are the main ones I have come across so far.

Thanks

**Comment by martonsagi** [comment]
Hi,

Thanks for the suggestion, I have added `.-()%#/+&?;*!` characters to be sure. Upcoming version will include this fix.

**Comment by martonsagi** [comment]
Tested, fixed it up and it's working now.
