### ISSUE TITLE
Problem with dowloaded symbols 

### ISSUE THREAD

**Issue by bostjanles** [martonsagi/al-object-designer#46]
There is a problem with downloaded symbols for a specific extension.  It produce error, so no object are show.
If I delete the corresponding file with symbols, there is no problem.

/C:/Users/Boštjan/Ap…esktop.main.js:3611 Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
	at ZipEntries.readEndOfCentral (c:\Users\Boštjan\.vscode\extensions\martonsagi.al-object-designer-0.1.2\node_modules\jszip\lib\zipEntries.js:168:23)
	at ZipEntries.load (c:\Users\Boštjan\.vscode\extensions\martonsagi.al-object-designer-0.1.2\node_modules\jszip\lib\zipEntries.js:256:14)
	at c:\Users\Boštjan\.vscode\extensions\martonsagi.al-object-designer-0.1.2\node_modules\jszip\lib\load.js:49:20

Symbol file via LinkedIn

**Comment by martonsagi** [comment]
Thanks, I'll check it out after the TechDays.

**Comment by martonsagi** [comment]
@bostjanles Do you have an update on this? Did you try re-downloading the problematic symbol as we discussed on TechDays?

Thanks,
Marton

**Comment by bostjanles** [comment]
I have tried with the newest app for Slovenian localization. And there is still an error. The app isr runtime, it is not signed. I will upload it to the LinkedIn now.

**Comment by martonsagi** [comment]
Thanks for the test files! The main issue is that runtime app symbols are encoded and can't be opened up as zip files. Therefore, the only action I can do is to skip runtime symbol processing.

**Comment by martonsagi** [comment]
Fix has been published alongside with v0.1.4
