### ISSUE TITLE
Discovering objects never finishes

### ISSUE THREAD

**Issue by NeverAskWhy** [martonsagi/al-object-designer#47]
Hi Márton,

I would really like to use your extension, however it never finished loading with my app. I think the reason is the OPPlus-Addon I'm depending on. It works as long as this Addon is not part of my workspace...any Ideas on what I could do here?

Best regards,
Jan

**Comment by martonsagi** [comment]
Hi Jan,

I think this will be the same issue as described in bug #46. There is an unreleased fix for this, can you test with [0.1.4-alpha.1](https://github.com/martonsagi/al-object-designer/blob/master/custom-builds/al-object-designer-0.1.4-alpha.1.vsix)?

Thanks,
Marton

**Comment by NeverAskWhy** [comment]
Hi Márton,

thanks I was already wondering if this is the same issue as with bug #46 but as I didn't see any error I thought it might be something else. 

I just installed your alpha and now it works :-). The AddOn doesn't show up though but I guess this is depending on their AddOn, right? Thank you very much for the quick fix! Closed from my side.

Best regards,
Jan

**Comment by NeverAskWhy** [comment]
Oh and by the way: the functionality to copy Events (and thus create the subscriber function by simply pasting) blew my mind yesterday :-)

**Comment by martonsagi** [comment]
> I just installed your alpha and now it works :-). The AddOn doesn't show up though but I guess this is depending on their AddOn, right? Thank you very much for the quick fix! Closed from my side.

Most likely you have received a runtime package of the add-on that is not a regular zip file. Unfortunately, those kind of packages cannot be processed as generic ones.

> Oh and by the way: the functionality to copy Events (and thus create the subscriber function by simply pasting) blew my mind yesterday :-)

Thanks! :) An update is coming to this feature that'll speed up copying even more! :D

**Comment by NeverAskWhy** [comment]
Sounds great! If I could add one wish while we’re talking about it: It would be great if one could also see the “System”-Events (OnAfterInsert, etc.), then one could have one stop for copying all events.

Von: Márton Sági <notifications@github.com>
Gesendet: Samstag, 28. Dezember 2019 15:32
An: martonsagi/al-object-designer <al-object-designer@noreply.github.com>
Cc: Jan Vorauer <jan.vorauer@vorcon.de>; State change <state_change@noreply.github.com>
Betreff: Re: [martonsagi/al-object-designer] Discovering objects never finishes (#47)


I just installed your alpha and now it works :-). The AddOn doesn't show up though but I guess this is depending on their AddOn, right? Thank you very much for the quick fix! Closed from my side.

Most likely you have received a runtime package of the add-on that is not a regular zip file. Unfortunately, those kind of packages cannot be processed as generic ones.

Oh and by the way: the functionality to copy Events (and thus create the subscriber function by simply pasting) blew my mind yesterday :-)

Thanks! :) An update is coming to this feature that'll speed up copying even more! :D
