### ISSUE TITLE
Filter resets after interacting with object

### ISSUE THREAD

**Issue by yannstlo** [martonsagi/al-object-designer#49]
Hi,

When using your "AMAZING" extension I discovered that when you search for an object then click on its name or the ellipsis to View, Preview or Run, once you click, the page gets reset. So if I had filtered using the search or the column headers, they get reset.

Again, amazing extension!
Thanks

**Comment by martonsagi** [comment]
Hi,

Thanks for the feedback! I think it can be fixed. Reload happens on AL file changes and the navigation creates a temporary file that is not filtered out from auto-reload.

**Comment by martonsagi** [comment]
Fixed! Changes in AL files will refresh the data behind the Object Designer window but filters and selected type will remain there.
I tried to navigate back to the same selected row if any, well it works more-or-less. You'll get scrolled back to the vicinity of your previous position.
