### ISSUE TITLE
Open Objects in Multi-Root Workspace with Non-AL Folders

### ISSUE THREAD

**Issue by marknitek** [martonsagi/al-object-designer#52]
If you have a multi-root workspace with a non AL-Folder as the first folder (for example a docs folder with markdown files), the feature to open/navigate to the al object/file does not work, because it tries to create the dummy .al file in the first folder.

Workaround: 
re-order the workspace folders to have an AL-Folder at the top
=> Doable but i would like to keep the docs at the top

Solution:
Detect the first AL-Folder by checking if an app.json file is in the root of that folder and use the first one that meets that criteria.

**Comment by martonsagi** [comment]
Hi Marco,

Thanks for the feedback! Makes sense, AL extenion's navigation only works if an AL project is the active workfolder.

I'll apply your suggestion as a short term fix. However, I'm looking into this in depth as I'm not satisfied with the current navigation experience in regards to symbols.

**Comment by martonsagi** [comment]
See #53. `Opening.al` has been replaced with a custom navigation logic.
