### ISSUE TITLE
"Opening.al" File Problem

### ISSUE THREAD

**Issue by aptMattKoe** [martonsagi/al-object-designer#53]
Hello,

I like this extension very well. But I get an error after I opend an object out of it.
The extension creates an "Opening...al." file in the ".alache" directory. This AL file does not work with the compiler.
![image](https://user-images.githubusercontent.com/57363453/72740499-115ae180-3ba6-11ea-8fd4-a20a75d93afc.png)
And when Start Debugging (F5) an another error appears what say, that the "opening" file could not be opened because it has no access.

Then I have to restart VS Code and it works again.

Any ideas?

**Comment by aptMattKoe** [comment]
Problem Solved on its own. No idea how but this problem is gone.

**Comment by martonsagi** [comment]
Actually, this is an old technical debt that I should have fixed already.
Object navigation creates a temp file to activate the built-in code navigation (ugly hack).

I'll leave the issue open not to forget this. (It's been fixed in AL Studio's Object Designer but that's another story :) )

**Comment by martonsagi** [comment]
This issue has been fixed by introducing a custom navigation feature that works independently of AL Language extension.
