### ISSUE TITLE
No Visual Studio Code Icon in Activity Bar at the left Side

### ISSUE THREAD

**Issue by PatrickKranig** [martonsagi/al-object-designer#58]
Hi,

i use this amazing extension (thanks) and missing a Icon Feature in Visual Studio Code in the Activity Bar at the left Side.

Can you implemented that?

I use it very often and don't want to go through the prompt every time to start the module.

Kind regards

**Comment by martonsagi** [comment]
Hi Patrick,

Thank you! I don't see any issue in adding a sidebar icon. Let me find an icon that's appropriate and I'll include it in the next update.

Marton

**Comment by PatrickKranig** [comment]
thank you, please correct me

Kind regards

**Comment by martonsagi** [comment]
This is how it would look like. What do you think?

![ALObjectDesignerSidebar](https://user-images.githubusercontent.com/18100709/79615634-8be2c100-8103-11ea-8d3b-83c2dfdf860e.gif)

**Comment by PatrickKranig** [comment]
Great yeah cool! When you can release it? And how can I update it in visual studio?

**Comment by martonsagi** [comment]
It's been just released a couple minutes ago. VSCode should automatically update the extension soon.

**Comment by PatrickKranig** [comment]
Cool thanks a lot!
