### ISSUE TITLE
"Multiple package versions found"

### ISSUE THREAD

**Issue by txeriff** [martonsagi/al-object-designer#59]
Hi, 

My extension has a dependency to another, however, the version it´s mentioning 
is no longer published. It always comes up with that. I don´t know how to fix it.

![Untitled](https://user-images.githubusercontent.com/43034938/80948268-a4ccc100-8de9-11ea-9988-048de4332b01.png)

**Comment by martonsagi** [comment]
Hi,

This warning is created when you have more than one version of the same package, e.g. Base App 15.1 and 16.1. 
The message stops when alpackage folders contain one version for each package. It's just a reminder to maintain symbols packages to avoid version mixing.
It won't have any effect on daily work.

**Comment by txeriff** [comment]
> 
> 
> Hi,
> 
> This warning is created when you have more than one version of the same package, e.g. Base App 15.1 and 16.1.
> The message stops when alpackage folders contain one version for each package. It's just a reminder to maintain symbols packages to avoid version mixing.
> It won't have any effect on daily work.

Thanks for that. deleting the old .app file from .alpackages folder made the trick!

**Comment by martonsagi** [comment]
You're welcome! I'm glad it worked out.
