### ISSUE TITLE
New List - some little fix

### ISSUE THREAD

**Issue by pierreLouise** [martonsagi/al-object-designer#6]
Hello 

On the New List  please replace 
PageType = Card; by PageType = List;

And
  group(Group) 
by : repeater(Control1)

**Comment by martonsagi** [comment]
Hi Pierre,

Thanks for the feedback! I have fixed the issue, it will be included in the next version.

**Comment by pierreLouise** [comment]
I have made a post this morning on the french BC community on yammer about you and your extension. Hope you have more contributors.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by martonsagi** [comment]
Thank you! There are so many use cases to test, I appreciate any help I receive.  :)
