### ISSUE TITLE
Multiple package versions found: Wrong app file fetched?

### ISSUE THREAD

**Issue by NKarolak** [martonsagi/al-object-designer#78]
Hi Márton,

this issue is related to #59, but still different.

The [AppSourceCop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop#configuration) requires to keep my own previous app version (not the Base App) in the .alpackages folder.

Your extension does not only say "Multiple package versions found" - it is also saying, that my previous app version is being used - and that appears wrong to me?

**Comment by martonsagi** [comment]
Hi Natalie,

Indeed, it was supposed to be a simple warning to "get your things together". However, if AppSourceCop demands such things, this function needs to evolve as well.

I have changed the search order, the latest package version will be used for processing. Also, there is a new option to turn off this warning completely: `alObjectDesigner.multiplePackageVersionWarning`.

![image](https://user-images.githubusercontent.com/18100709/95122690-2c2faf00-0751-11eb-8edd-23b6ab813a2e.png)

**Comment by martonsagi** [comment]
PS.: it has been published on Marketplace with v0.2.4

**Comment by NKarolak** [comment]
Great, thank you :-)
